name: Waka Readme New

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '*/2 * * * *'

jobs:
  update-readme:
    name: WakaTime
    runs-on: ubuntu-latest
    steps:
      - uses: barthachijuu/waka-profile-stats@main
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
