name: Waka Readme Newwww

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 */12 * * *'

jobs:
  update-readme:
    name: WakaTime
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: "False"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SYMBOL_VERSION: 3
          SHOW_TIMEZONE: "False"
          SHOW_COMMIT: "False"
          COMMIT_MESSAGE: "✅README updated"
          SHOW_UPDATED_DATE: "False"
          SHOW_LANGUAGE: "True"
          
