name: Waka Readme New

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '*/2 * * * *'

jobs:
  update-charts:
    name: WakaTime
    runs-on: ubuntu-latest
    steps:
      - uses: dvjn/wakatime-charts@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
